#!/usr/bin/env bash
# Scale measurement of the HQ consumer (bench/README.md).
#
#   bench.sh            run everything: start, load phase, client phase, print the tables (the stack stays up)
#   bench.sh down       remove the bench stack
#
# Knobs (environment): BROKERS (10) small Kafka brokers, PER_BRANCH (200) records waiting per broker in the load
# phase, LEVELS ("100 300 1000") number of registered branches at which the client phase measures.
#
# Load phase: one branch per broker with PER_BRANCH records already in its topic (each a different sale date, as a
# branch's producer leaves after a long outage), then HQ connects. Measures records per second through parse,
# validation, upsert, receipt and ack, with nothing else on the consumer.
# Client phase: more registry rows pointing at the same brokers (they join the same consumer group, so they receive
# nothing) to measure what one connected branch costs in the consumer JVM: heap after GC, threads, TCP connections,
# resident memory, idle CPU, and how long the registry refresh takes to connect them all.
set -euo pipefail
cd "$(dirname "$0")"
export MSYS_NO_PATHCONV=1

BROKERS=${BROKERS:-10}
PER_BRANCH=${PER_BRANCH:-200}
LEVELS=${LEVELS:-"100 300 1000"}
compose() { docker compose -f docker-compose.yml -f brokers.compose.yml "$@"; }
sql() { docker exec -i bench-db psql -U hq_app -d hq_sales -tAq -v ON_ERROR_STOP=1 "$@"; }
consumer() { docker exec bench-consumer "$@"; }
kafka() { local i=$1; shift; docker exec -i "bench-kafka-$i" "/opt/kafka/bin/$@"; }
code() { printf 'BR%04d' "$1"; }

generate_brokers() {
  {
    echo "# Generated by bench.sh: $BROKERS single-node PLAINTEXT brokers with a small heap. Not committed."
    echo "services:"
    for i in $(seq 1 "$BROKERS"); do
      cat <<EOF
  kafka-$i:
    image: apache/kafka:4.3.1
    container_name: bench-kafka-$i
    environment:
      CLUSTER_ID: $(openssl rand -base64 16 | tr '+/' '-_' | tr -d '=')
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-$i:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-$i:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_HEAP_OPTS: -Xmx192m -Xms128m
    networks: [bench]
EOF
    done
  } > brokers.compose.yml
}

wait_until() { # wait_until <seconds> <description> <command...>
  local limit=$1 what=$2; shift 2
  local start=$SECONDS
  until "$@"; do
    if (( SECONDS - start > limit )); then echo "timeout waiting for $what" >&2; return 1; fi
    sleep 2
  done
}

migrated() { sql -c "select 1 from branch limit 0" > /dev/null 2>&1; }
connected() { [[ "$(docker logs bench-consumer 2>&1 | grep -c 'Connected to branch')" -ge "$1" ]]; }
# Every record ends up in one of the two tables; a rejected one counts as handled (and is reported)
handled() { [[ "$(sql -c 'select (select count(*) from branch_daily_sales) + (select count(*) from dead_letter)')" -ge "$1" ]]; }
# The two contract topics, as the branch's kafka-init creates them
topic() { kafka "$1" kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --partitions 1 --replication-factor 1 --topic "$2" > /dev/null 2>&1; }

register() { # register <from> <to>: branch i reads broker ((i-1) mod BROKERS)+1
  sql -c "insert into branch (branch_code, name, kafka_bootstrap)
          select 'BR' || lpad(i::text, 4, '0'), 'Bench ' || i, 'kafka-' || ((i - 1) % $BROKERS + 1) || ':9092'
            from generate_series($1, $2) i on conflict (branch_code) do nothing"
}

# One record per line as "key|json", PER_BRANCH different sale dates, 4 lines each (~470 bytes), eventId a UUID v4
records() {
  local branch=$1 d day
  for d in $(seq 0 $((PER_BRANCH - 1))); do
    day=$(date -d "2020-01-01 + $d days" +%F)
    printf '%s|{"schemaVersion":1,"eventId":"%08x-%04x-4%03x-%04x-%012x","branchCode":"%s","saleDate":"%s","revision":1,"confirmedAt":"%sT21:45:00+07:00","currency":"THB","totalAmount":"41870.50","lines":[{"categoryCode":"BEVERAGE","amount":"18200.00","quantity":410},{"categoryCode":"SNACK","amount":"12050.00","quantity":395},{"categoryCode":"READY_MEAL","amount":"9120.50","quantity":152},{"categoryCode":"HOUSEHOLD","amount":"2500.00","quantity":37}]}\n' \
      "$branch" $((RANDOM << 17 | RANDOM << 2 | RANDOM & 3)) $RANDOM $((RANDOM % 4096)) $((0x8000 | RANDOM & 0x3fff)) \
      $(((RANDOM << 33 | RANDOM << 18 | RANDOM << 3 | RANDOM & 7) & 0xFFFFFFFFFFFF)) "$branch" "$day" "$day"
  done
}

measure() { # measure <branches> <connect time>
  consumer jcmd 1 GC.run > /dev/null
  local heap threads sockets rss cpu
  heap=$(consumer jcmd 1 GC.heap_info | sed -n 's/.*used \([0-9]*\)K.*/\1/p' | head -1)
  threads=$(consumer sh -c 'ls /proc/1/task | wc -l')
  sockets=$(consumer sh -c 'cat /proc/1/net/tcp /proc/1/net/tcp6 | grep -c " 01 "')
  # docker stats prints MiB or GiB; both as MB
  read -r rss cpu < <(docker stats --no-stream --format '{{.MemUsage}} {{.CPUPerc}}' bench-consumer \
    | awk '{ v = $1; if ($1 ~ /GiB/) v *= 1024; printf "%d %s\n", v, $NF }')
  printf '| %s | %s | %s MB | %s | %s | %s MB | %s |\n' "$1" "$2" "$((heap / 1024))" "$threads" "$sockets" "$rss" "$cpu" >> "$RESULTS"
}

down() { docker compose -f docker-compose.yml -f brokers.compose.yml down -v --remove-orphans 2>/dev/null || true; }

if [[ "${1:-}" == "down" ]]; then
  [[ -f brokers.compose.yml ]] || generate_brokers
  down
  exit 0
fi

RESULTS=$(mktemp)
echo "== start: $BROKERS brokers, 1 consumer, 1 database"
generate_brokers
down
compose up -d --build --quiet-pull
wait_until 120 "the consumer to migrate the database" migrated
for i in $(seq 1 "$BROKERS"); do
  wait_until 120 "broker $i to create its topics" topic "$i" branch-sales.daily-summary
  topic "$i" branch-sales.receipt
done

echo "== load phase: $BROKERS branches x $PER_BRANCH records"
for i in $(seq 1 "$BROKERS"); do
  records "$(code "$i")" | kafka "$i" kafka-console-producer.sh --bootstrap-server localhost:9092 \
    --topic branch-sales.daily-summary --property parse.key=true --property key.separator='|' > /dev/null &
done
wait
total=$((BROKERS * PER_BRANCH))
start=$SECONDS
register 1 "$BROKERS"
wait_until 120 "$BROKERS branches to connect" connected "$BROKERS"
connect=$((SECONDS - start))
wait_until 600 "$total records to be handled" handled "$total"
elapsed=$((SECONDS - start))
receipts=0
for i in $(seq 1 "$BROKERS"); do
  n=$(kafka "$i" kafka-get-offsets.sh --bootstrap-server localhost:9092 --topic branch-sales.receipt | awk -F: '{s+=$3} END {print s+0}')
  receipts=$((receipts + n))
done
dead=$(sql -c 'select count(*) from dead_letter')
{
  echo "### Load phase"
  echo
  echo "| Branches (brokers) | Records waiting | Connected in | All stored + receipts in | Records/s total | Records/s per branch | Receipts | dead_letter |"
  echo "|---|---|---|---|---|---|---|---|"
  printf '| %s | %s | %s s | %s s | %s | %s | %s | %s |\n' "$BROKERS" "$total" "$connect" "$elapsed" \
    "$((total / (elapsed > 0 ? elapsed : 1)))" "$((PER_BRANCH / (elapsed > 0 ? elapsed : 1)))" "$receipts" "$dead"
  echo
  echo "### Client phase"
  echo
  echo "| Branches | Connected in | Heap after GC | Threads | TCP connections | RSS | CPU (idle) |"
  echo "|---|---|---|---|---|---|---|"
} > "$RESULTS"
sleep 5
measure "$BROKERS" "$connect s"

echo "== client phase: $LEVELS branches"
for level in $LEVELS; do
  current=$(sql -c 'select count(*) from branch')
  start=$SECONDS
  register $((current + 1)) "$level"
  wait_until 900 "$level branches to connect" connected "$level"
  measure "$level" "$((SECONDS - start)) s"
done

echo
echo "Consumer JVM: $(consumer java -version 2>&1 | head -1), JAVA_OPTS=${BENCH_JAVA_OPTS:--Xmx2g}; brokers: apache/kafka:4.3.1 -Xmx192m; Docker: $(docker info --format '{{.NCPU}} CPUs, {{.MemTotal}} bytes')"
echo
cat "$RESULTS"
rm -f "$RESULTS"
echo
echo "Stack is still running (docker compose -p branch-sales-bench ps). Remove it with: bench.sh down"
